<a href="https://colab.research.google.com/github/lluvia23/unidad1/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy es una libreria de python.
numpy se utiliza para trabajar con
matrices o arreglos
numpy es la agreviatura de "python numerico"
tambien tiene funciones para trabajar en el dominio del algebra lineal , la transformada y las matrices
en python tenemos listas que sirven como matrices,pero son lentas de procesar.
numpy tiene como objetivo proporcionar un objecto de matriz que sea 50 veces mas rapido que las listas tradicionales

In [1]:
#primero tenemos que importar la libreria
import numpy

arreglo = numpy.array([1,2,3,4,5])
print(arreglo)

[1 2 3 4 5]


numpy como np
numpu generalmente se importa bajo el alias np son un nombre alternativo para referirse a la misma cosa

In [6]:
import numpy as np
  arreglo = np.array ([6,7,8,9,10])
    print(arreglo)

[ 6  7  8  9 10]


comprobando la version de numpy
la cadena de la version se almacena en el atributo _version_


In [10]:
import numpy as np
print(np._version_)

2.0.2


numpy creando matrices
crear un objecto  ndarray de numpy
numpy se utiliza para trabajar con matrices. el objetivo de matriz se llama ndarray
podemos crear un numpy ndarray utilizando la funcion array()

In [30]:
import numpy as np
  arreglo = np.array(["raul","ana","kimberly","jazmin"])
  print(arreglo)
  print(type(arreglo))

IndentationError: unexpected indent (ipython-input-1367814783.py, line 2)

dimesion en matrices
una dimension en matrices es un nivel de profundidad de matriz(matrices anidada)
una matriz anidada contiene matrices como elementos
matrices 0-D, son elementos de una matriz.cada valor de una matriz es una matriz 0-D.
ejemplo: crea una matriz 0-D con un valor de 42

In [20]:
import numpy as np

arreglo = np.array(42)

print(arreglo)

42


matrices 1-D
una matriz que tiene  matrices 0-D como elementos se denomina matriz
unidimension o 1-D.
estas son las matrices mas comunes y basicas
ejemplo: crea una matriz de 1-D que tengan los valores 1,2,3,4,5


In [23]:
import numpy as np
arreglo = np.array([1,2,3,4,5])

print(arreglo)

[1 2 3 4 5]


matrices 2-D
una matriz se denomina 1-D como elementos se denominan matriz 2-D
a menudo se utilizan  para representar matrices de segundo orden .numpy tiene un submodulo completo dedicado a operaciones con matrices llamado numpy mat.
ejemplo: crea una matriz 2-D que contenga  dos matrices con los valores 1,2,3,4,5 y 6

In [25]:
import numpy as np
arreglo = np.array([[1,2,3],[4,5,6]])

print(arreglo)

[[1 2 3]
 [4 5 6]]


matrices 3-D
una matriz que tiene matrices 2D se denomina matriz 3-D
estas matrices se utilizan para representar  una tercer matriz
ejemplos:crea uan matriz 3D con dos bidimensionales,ambas conteniendo matrices con valores 1,2,3 y 4,5,6


In [29]:
import numpy as np
arreglo = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(arreglo)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
