<a href="https://colab.research.google.com/github/lluvia23/unidad1/blob/main/practica6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

lluvia guadalupe encinas juarez-24 de septiembre del 2025
practica 6- cortar arreglos numpy
--------------------
slice en python significa tomar elementos de un indice  determinada a otro determinado indice.

que es slice en lugar del indice de esta manera: [start:end]
sino pasamos el inicio se concidera 0
sino pasamos el final su longitud es considerada una matriz de una dimension
-------------------------
ejemplo:([1,2,3,4,5,6,7])
cortar los elementos del indice 1 al indice 5
------------




In [3]:
import numpy as np
arreglo=np.array([1,2,3,4,5,6,7])
print(arreglo[1:5])


[2 3 4 5]


ejemplo 2:
([1,2,3,4,5,6,7])
cortar del indice 4 hasta la matriz


In [4]:
import numpy as np
arreglo=np.array([1,2,3,4,5,6,7])
print(arreglo[4:])


[5 6 7]


ejemplo 3:
([1,2,3,4,5,6,7])
cortar elementos desde el principio hasta el indice 5

In [7]:
import numpy as np
arreglo=np.array([1,2,3,4,5,6,7])
print(arreglo[:5])

[1 2 3 4 5]


ejemplo 4:
([1,2,3,4,5,6,7])
corte negativo,utilizamos el operador "menos" para hacer referencia a un indice hasta el final
-----------------------------
cortar del indice 3 desde el final al indice 1 desde el final

In [8]:
import numpy as np
arreglo=np.array([1,2,3,4,5,6,7])
print(arreglo[-3:-1])


[5 6]
